# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-tutorial-of-markdown
title: 量潮Markdown教程
author: 量潮科技
description: 量潮Markdown教程
# Jupyter Book Config
only_build_toc_files: true